### ISSUE TITLE
Uncaught exception when pressing <enter> without operand

### ISSUE THREAD

**Issue by hollie** [fastrgv/Interval-RPN-Calculator#1]
Hello,

first of all: I'll be keeping an eye on this software. I've been searching for a HP-compatible terminal calculator for some time. Your project looks promising! Thanks for posting it publicly.

Just a minor remark: when I start the program and accidentally press <enter> immediately after starting the program it crashes with:

```
libc++abi.dylib: terminating with uncaught exception of type gaol::input_format_error: std::exception
```

Maybe this is something that should not crash the program?

Best regards,
 Lieven.

**Comment by fastrgv** [comment]
Thanks, Lieven,
I shall be working toward better exception handling, starting with your
problem.  I welcome not only error reports but other suggestions, including
suggested code modifications.  Watch for updates.
Rod

**Comment by fastrgv** [comment]
I just added an updated "irpn.adb" that fixes the immediate problem.  If
you cannot recompile it yourself, you will need to wait for my next update,
coming soon.  Rod

**Comment by hollie** [comment]
Hello Rob,

perfect, thanks for the fast reply and fix.

When I come up with suggestions I will add them to this ticketing system.

Best,
 Lieven
